#!/usr/bin/env bash
set -euo pipefail
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
export PROGRESS_DIR="$REPO_DIR/progress/sprint_10"
export PROFILE_FILE="$REPO_DIR/progress/sprint_10/oracle-layout-4k-redo.fio"
export SPRINT_LABEL="Sprint 10 Higher Performance Multi"
export NAME_PREFIX="bv4db-oracle10-hp-multi-run"
export RUN_LEVEL="integration"
export FIO_RUNTIME_SEC="${FIO_RUNTIME_SEC:-600}"
export STORAGE_LAYOUT_MODE="multi_volume"
export ARTIFACT_PREFIX="oracle-hp-multi-4k-redo-integration"
export VPU_DATA="20"
export VPU_REDO="20"
export VPU_FRA="20"
export COMPUTE_OCPUS="${COMPUTE_OCPUS:-8}"
export COMPUTE_MEMORY_GB="${COMPUTE_MEMORY_GB:-32}"
exec "$REPO_DIR/tools/run_bv_fio_oracle.sh"
